//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fedisal_Becario.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FedisalEntities1 : DbContext
    {
        public FedisalEntities1()
            : base("name=FedisalEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Becario> Becario { get; set; }
        public virtual DbSet<BitacoraIncidentes> BitacoraIncidentes { get; set; }
        public virtual DbSet<Carrera> Carrera { get; set; }
        public virtual DbSet<Ciclo> Ciclo { get; set; }
        public virtual DbSet<Desembolso> Desembolso { get; set; }
        public virtual DbSet<InformacionPersonal> InformacionPersonal { get; set; }
        public virtual DbSet<NivelEducativo> NivelEducativo { get; set; }
        public virtual DbSet<Nota> Nota { get; set; }
        public virtual DbSet<PresupuestoBecas> PresupuestoBecas { get; set; }
        public virtual DbSet<ProgramaBecas> ProgramaBecas { get; set; }
        public virtual DbSet<TipoDesembolso> TipoDesembolso { get; set; }
        public virtual DbSet<TipoIncidente> TipoIncidente { get; set; }
        public virtual DbSet<Universidad> Universidad { get; set; }
    }
}
