//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fedisal_Becario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Becario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Becario()
        {
            this.BitacoraIncidentes = new HashSet<BitacoraIncidentes>();
            this.Ciclo = new HashSet<Ciclo>();
            this.PresupuestoBecas = new HashSet<PresupuestoBecas>();
        }
    
        public string idBecario { get; set; }
        public Nullable<System.DateTime> fechaInicio { get; set; }
        public Nullable<System.DateTime> fechaFin { get; set; }
        public Nullable<int> idInformacion { get; set; }
        public string idPrograma { get; set; }
        public Nullable<int> idUniversidad { get; set; }
        public Nullable<int> idCarrera { get; set; }
        public Nullable<int> idNivelEducativo { get; set; }
        public string contrasenna { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BitacoraIncidentes> BitacoraIncidentes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ciclo> Ciclo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PresupuestoBecas> PresupuestoBecas { get; set; }
        public virtual Carrera Carrera { get; set; }
        public virtual InformacionPersonal InformacionPersonal { get; set; }
        public virtual NivelEducativo NivelEducativo { get; set; }
        public virtual ProgramaBecas ProgramaBecas { get; set; }
        public virtual Universidad Universidad { get; set; }
    }
}
