//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fedisal_Becario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InformacionPersonal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InformacionPersonal()
        {
            this.Becario = new HashSet<Becario>();
        }
    
        public int idInformacion { get; set; }
        public string nombres { get; set; }
        public string apellidos { get; set; }
        public string dui { get; set; }
        public Nullable<System.DateTime> fechaNacimiento { get; set; }
        public string direccionResidencia { get; set; }
        public string telefono { get; set; }
        public string correoElectronico { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Becario> Becario { get; set; }
    }
}
