//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fedisal_Becario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PresupuestoBecas
    {
        public int idPresupuesto { get; set; }
        public Nullable<decimal> libro { get; set; }
        public Nullable<decimal> colegiatura { get; set; }
        public Nullable<decimal> manutencion { get; set; }
        public Nullable<decimal> matricula { get; set; }
        public Nullable<decimal> otros { get; set; }
        public Nullable<decimal> trabajoGraduacion { get; set; }
        public string idBecario { get; set; }
    
        public virtual Becario Becario { get; set; }
    }
}
